### ISSUE TITLE
[TODO] 6/18-6/20

### ISSUE THREAD

**Issue by kevinchunyu** [jakobzhao/vgi#3]
[TODO]:
-  [x] Style dashboard per click of location
-  [x] Change dashboard size to fit to page (currently `height: 100%`  includes the offset of the nav bar)
-  [ ] Construct filter function to show Damron code on dashboard
-  [x] Finish styling of slider inputs (given range from x year to y year)
