### ISSUE TITLE
TODO (8/21 - 8/25)

### ISSUE THREAD

**Issue by kevinchunyu** [jakobzhao/vgi#4]
// Higher Priority for this week
- [x] Map style selection
- [x] Add user suggest observation functionalities
- [ ] Integrate sign-in features with conjunction with user suggestion availability

// Less Priority for this week
- [ ] Damron Code & type filters
- [ ] navbar navigation (easier content like introduction page can be filled with content)
